### ISSUE TITLE
Question: How is the key hash generated?

### ISSUE THREAD

**Issue by v217** [zotero/translation-server#150]
I use the [wikipedia getCitation api](https://en.wikipedia.org/api/rest_v1/#/Citation/getCitation) which is based on [translation-server](https://www.mediawiki.org/wiki/Citoid/API), my question is: 
How is the `key:` value in the following example `KG7GUFFB` generated? Thanks!
```yaml
abstractNote: 'I use the wikipedia getCitation api which is based on translation-server,
  my question is: How is the key: value in the following example KG7GUFFB generated?
  Thanks!'
accessDate: '2022-12-09'
creators: []
itemType: webpage
key: KG7GUFFB
language: en
shortTitle: Question
tags: []
title: "Question: How is the key hash generated? \xB7 Issue #150 \xB7 zotero/translation-server"
url: https://github.com/zotero/translation-server/issues/150
version: 0
websiteTitle: GitHub
```
(I transformed the json-response to yaml for readability.)
